language: bash

env:
- APIKEY="DJiKvMPbfAGVbLh/2BoBMkDjD2TxKSZTczpVPQ7T8R0=" SUITE_ID=19 BROWSER=Chrome USER_VARIABLES="name1=javas,input=admin" TAG=Sequential0 BASE_URL="http://the-internet.herokuapp.com/" SEQUENTIAL_EXECUTION=TRUE

before_script:
- curl -O https://devcquserfiles.s3.amazonaws.com/22/8e479e1abb6c43d78e230f8d6a112686/cloudqa-travisci.sh

script:
- bash cloudqa-travisci.sh

